fixlyft/urls.py
from django.urls import path, include
from .import views
from .otp import phone_validation, validate_otp
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/schedule-pickup/', views.SchedulePickup.as_view(), name='submit'),
    path('phonevalidation/', phone_validation, name='phone'),
    path('otpverification/', validate_otp, name='otp'),
    path('shops-schedule-pickup/', views.MobileShopSearch.as_view(), name='schedule'),
    path('shops/', views.shops, name='shops_table'),
    path('offers/', views.offers, name='offers'),
    path('delivery/', views.delivery, name='delivery'),
    path('support/', views.support, name='support'),
]

fixlyft_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from staffs.views import all_pickups, UpdatePickup
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('fixlyftadminff/', admin.site.urls),
    path('', include('fixlyft.urls')),
    path('allpickups/', all_pickups, name='allpickups'),
    path('<int:pk>/update/', UpdatePickup.as_view(), name='update'),
    path('stafflogout/', auth_views.LogoutView.as_view(template_name='staffs/logout.html'), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fixlyft/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.urls import reverse
from fixlyft_project.utils import unique_slug_generator
from django.db.models.signals import pre_save
#from PIL import Image
from django.core.validators import MinValueValidator, MaxValueValidator
from fixlyft_project.utils import IntegerRangeField
# Create your models here.
phone_regex = RegexValidator(regex = r'^[7-9][0-9]{9}$')

SERVICES_CHOICES = (
    ('0', 'SELECT_SERVICES'),
    ('Smartphone / Tablet', 'Smartphone / Tablet'),
    ('Laptop / Pc', 'Laptop / Pc'),
    ('Gaming Consoles', 'Gaming Consoles'),
)

class MobileShop(models.Model):
    shop_name = models.CharField(max_length=50)
    shop_img = models.ImageField(default='default.png', upload_to='shop_images', help_text="Please Upload Image in 90x90 pixels size only for better view")
    slug = models.SlugField(max_length=200, null=True, blank=True)
    rating = IntegerRangeField(min_value=1, max_value=5, default=1)
    city_name = models.CharField(max_length=25)
    address = models.CharField(max_length=100)
    pincode = models.CharField(max_length=15)
    phone = models.CharField(validators = [phone_regex], max_length=12)
    date_added = models.DateTimeField(default=timezone.now)
    services = models.CharField(choices=SERVICES_CHOICES, max_length=30, default=None)
    premium = models.BooleanField(default=False)

    class Meta:
        ordering = ['-premium', '-rating']


    def __str__(self):
        return self.shop_name

    
    def get_absolute_url(self):
        return reverse('schedule', kwargs={'pk': self.pk})

#    def save(self, *args, **kwargs):
#        super().save(*args, **kwargs)
 #       img = Image.open(self.shop_img.path)
 #       if img.height > 90 or img.width > 90:
  #          output_size = (90, 90)
  #          img.thumbnail = (output_size)
  #          img.save(self.shop_img.path)

    @property
    def ImageUrl(self):
        try:
            url = self.shop_img.url
        except:
            url = ''
        return url


class PickUP(models.Model):
    customer_name = models.CharField(max_length=30)
    mobileshop = models.ForeignKey(MobileShop, on_delete=models.CASCADE, null=True)
    mobile_number = models.CharField(validators = [phone_regex], max_length=12)
    device_name = models.CharField(max_length=50)
    complaint = models.CharField(max_length=50)
    place = models.CharField(max_length=50)
    completed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=timezone.now) 

    class Meta:
        ordering = ['-timestamp',] 


    def __str__(self):
        return self.customer_name

    def get_absolute_url(self):
        return reverse('schedule')

class SmsOTP(models.Model):
    phone = models.CharField(validators = [phone_regex], max_length = 15, unique=True)
    otp = models.CharField(max_length=9, blank=True, null=True)
    count = models.IntegerField(default=0, help_text='Number of otp sent')
    validated = models.BooleanField(default=False, help_text='True if OTP is verified')
    otp_session_id = models.CharField(max_length=120, null=True, default="")
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.phone) + ' is sent ' + str(self.otp)

class OfferImages(models.Model):
    link = models.URLField(max_length=999)
    offer_img = models.ImageField(default='c.png', upload_to='offer_images', help_text="Please upload images in 660x300 pixels only for better view")
    date_added = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_added']

    
#    def save(self, *args, **kwargs):
 #       super().save(*args, **kwargs)
#        img = Image.open(self.offer_img.path)
#        if img.height > 660 or img.width > 300:
#            output_size = (660, 300)
#            img.thumbnail = (output_size)
  #          img.save(self.offer_img.path)

    @property
    def ImageUrl(self):
        try:
            url = self.offer_img.url
        except:
            url = ''
        return url


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=MobileShop)

staffs/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager


# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

staffs/views.py
from django.shortcuts import render
from fixlyft.models import PickUP as SchedulePickUP
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import UpdateView
# Create your views here.

@staff_member_required
def all_pickups(request):
    pickups = SchedulePickUP.objects.filter(completed=False)
    
    context = {
        'pickups': pickups
    }

    return render(request, 'staffs/pickup.html', context)


class UpdatePickup(UpdateView):
    model = SchedulePickUP
    fields = ['completed',]
    template_name = 'staffs/update.html'

staffs/templates/staffs/logout.html
{% extends "fixlyft/base.html" %}
{% block content %}
<div class="container login-container"></div>
 <div class="form-group">
      <h2 class="login-heading">You have been Logged Out</h2>
        <div class="form-group">
            <div class="mid">
               <a class="btn btn-info btn-lg" href="{% url 'index' %}">Go to Home Page</a>
            </div>
        </div>
        <div class="class-line"></div>
  </div>
</div>
{% endblock content %}

staffs/templates/staffs/pickup.html
{% extends "fixlyft/base.html" %}
{% block content %}
{% load humanize %}

<div class="container">
    <div class="row">
        <div class="col-12" style="overflow: auto;white-space: nowrap;margin-top: 15px;">
            <table class="table table-responsive table-bordered table-striped">
                <thead>
                    <tr>
                    <th>Date and Time</th>
                    <th>Customer Name</th>
                    <th>Mobile Number</th>
                    <th>Mobile Shop</th>
                    <th>Device</th>
                    <th>Complaint</th>
                    <th>Call Customer</th>
                    <th>Mark as Completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pickup in pickups %}
                    <tr>

                    <td>{{ pickup.timestamp }}</td>
                    <td>{{ pickup.customer_name }}</td>
                    <td>{{ pickup.mobile_number }}</td>
                    <td>{{ pickup.mobileshop }}</td>
                    <td>{{ pickup.device_name }}</td>
                    <td>{{ pickup.complaint }}</td>
                    <td><a href="tel:{{ pickup.mobile_number }}"><button >Call Customer</button></a></td>
                    <td><button onclick="updateForm('{% url 'update' pickup.pk %}')">Mark as Completed</button></td>
                     </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<a href="{% url 'logout' %}">Logout</a>

<div class="modal"  id="fModal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Confirm</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <div class="modal-body">
            <form name="updateTable" id="updateTable" action="" method="POST">
                {% csrf_token %}
                <input type="checkbox" name="completed" id="id_completed"> Confirm<br><br>
                <button type="submit" class="submit-button">Update</button>
            </form>
        </div>
    </div>
</div>

<script>
    var frmUrl;
    function updateForm(pk){
        frmUrl = pk;
        document.getElementById('updateTable').action = frmUrl;
        $('#fModal').modal();
    }
</script>
{% endblock %}

staffs/templates/staffs/update.html
<div>
    <form method="POST">
        {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
    </form>
</div>